packaging_format = 2

id = "eleventy"
name = "Eleventy"
description.en = "Simpler site generator"
description.fr = "Générateur de site plus simple"

version = "3.1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://www.11ty.dev/"
admindoc = "https://www.11ty.dev/docs/"
code = "https://github.com/11ty/eleventy/"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/eleventy"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/11ty/eleventy/archive/refs/tags/v3.1.0.tar.gz"
        sha256 = "5c64aa37c1ee10a1d35989534f976efd28375b2bff4ed4e8c40a1bb9581fbf07"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["public"]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
