packaging_format = 2

id = "eleventy"
name = "Eleventy"
description.en = "Simpler site generator. Transforms a directory of templates (of varying types) into HTML"
description.fr = "Générateur de site plus simple. Transforme un répertoire de modèles (de différents types) en HTML"

version = "3.0.0~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://www.11ty.dev/"
admindoc = "https://www.11ty.dev/docs/"
code = "https://github.com/11ty/eleventy/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/11ty/eleventy/archive/refs/tags/v3.0.0.tar.gz"
        sha256 = "ab6c0f51f733e865de347213b63c5f3383c06ce325db347a89c57eed313f0e21"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["src", "public"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
