#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

install_dir="/var/www/$app"
mkdir -p "$install_dir"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app: "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Simpler site generator" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL ELEVENTY
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app npm init -y
	ynh_hide_warnings ynh_exec_as_app npm install @11ty/eleventy@$(ynh_app_upstream_version) --save-dev
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="eleventy.config.cjs" --destination="$install_dir/eleventy.config.cjs"
ynh_config_add --template="package.json" --destination="$install_dir/package.json"
mkdir -p $install_dir/src/_includes
mkdir -p $install_dir/src/css
ynh_config_add --template="base.njk" --destination="$install_dir/src/_includes/base.njk"
ynh_config_add --template="../sources/index.md" --destination="$install_dir/src/index.md"
ynh_config_add --template="../sources/style.css" --destination="$install_dir/src/css/style.css"

chown -R $app: "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
