#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=7

# Install Nodejs
ynh_exec_warn_less ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir"

ynh_add_config --template="../sources/index.md" --destination="$data_dir/src/index.md"
ynh_add_config --template="../sources/style.css" --destination="$data_dir/src/style.css"
mv "../sources/_includes" "$data_dir/src/_includes"

chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_add_nginx_config

env_path="$PATH"
# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description="Simpler site generator" --log="/var/log/$app/$app.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="../conf/.eleventy.js" --destination="$install_dir/.eleventy.js"

chmod 400 "$install_dir/.eleventy.js"
chown $app:$app "$install_dir/.eleventy.js"

#=================================================
# INSTALL ELEVENTY
#=================================================
ynh_script_progression --message="Installing $app..." --weight=10

pushd $install_dir
 	ynh_use_nodejs
	ynh_exec_warn_less sudo -u $app env $ynh_node_load_PATH $ynh_npm init -y
	ynh_exec_warn_less sudo -u $app env $ynh_node_load_PATH $ynh_npm install @11ty/eleventy --save-dev
popd

#=================================================
# GENERIC FINALIZATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
